import {
  agentJsonFieldDescription,
  agentListFieldDescription,
} from '../objects/agent-field-contract.js';
import {
  applicationStatuses,
  opportunityStatuses,
} from '../objects/lifecycle.js';
import {
  accountStatuses,
  recommendationDecisions,
  taskAssigneeRoles,
  taskKanbanColumns,
  taskStatuses,
  taskTypes,
} from '../objects/workflow.js';
import { sourceProviderIds } from '../source-provider-ids.js';

export type FieldKind =
  | 'text'
  | 'textarea'
  | 'select'
  | 'number'
  | 'checkbox'
  | 'datetime'
  | 'date'
  | 'combo';

export interface ComboFieldConfig {
  allowCreate?: boolean;
  className: string;
  createKey?: string;
  displayKeys?: string[];
  labelKey: string;
  snapshotKey?: string;
  valueKey?: string;
}

export interface ReferenceFieldConfig {
  className?: string;
  editable?: boolean;
  labelKey?: string;
  labelKeys?: string[];
  resourceSlug?: string;
}

export interface ReferenceOption {
  href?: string;
  label: string;
  missing?: boolean;
  value: string;
}

export type ReferenceOptionsByField = Record<string, ReferenceOption[]>;

export interface ResourceField {
  key: string;
  label: string;
  kind: FieldKind;
  required?: boolean;
  options?: string[];
  combo?: ComboFieldConfig;
  reference?: ReferenceFieldConfig;
  description?: string;
  placeholder?: string;
  rows?: number;
  defaultValue?: string | number | boolean;
  /**
   * Coerce the submitted value before writing. Use for fields whose input
   * renders as a string (e.g. a `select`) but whose model column is numeric:
   * blank becomes `null`, otherwise the value is `Number(...)`-coerced.
   */
  coerce?: 'number';
}

export interface AdminResource {
  slug: string;
  className: string;
  label: string;
  singularLabel: string;
  description: string;
  icon: string;
  orderBy: string;
  rowAction?: 'edit' | 'none';
  tableColumns: string[];
  fields: ResourceField[];
}

const pipelineStates = [...opportunityStatuses];

const resourceSlugByClassName = new Map<string, string>([
  ['Achievement', 'achievements'],
  ['AgentRun', 'agent-runs'],
  ['Application', 'applications'],
  ['ApplicationMaterialComment', 'application-material-comments'],
  ['Attachment', 'attachments'],
  ['CandidateProfile', 'candidate-profiles'],
  ['Company', 'companies'],
  ['CompanyResearch', 'company-research'],
  ['Decision', 'decisions'],
  ['Education', 'education'],
  ['EmploymentRole', 'roles'],
  ['EvaluationScore', 'evaluation-scores'],
  ['Experience', 'experience'],
  ['Fact', 'facts'],
  ['FactCandidate', 'fact-candidates'],
  ['FactIntake', 'fact-intakes'],
  ['Opportunity', 'opportunities'],
  ['Project', 'projects'],
  ['ResumeAsset', 'resume-assets'],
  ['ResumeTailoringConfig', 'resume-tailoring-configs'],
  ['ResumeVariant', 'resume-variants'],
  ['Source', 'sources'],
  ['SourceCrawl', 'source-crawls'],
  ['SourceCrawlItem', 'source-crawl-items'],
  ['Task', 'tasks'],
]);

const referenceByFieldKey: Record<string, ReferenceFieldConfig> = {
  achievementId: {
    className: 'Achievement',
    labelKeys: ['title', 'summary'],
    resourceSlug: 'achievements',
  },
  agentRunId: {
    className: 'AgentRun',
    labelKeys: ['runType', 'status'],
    resourceSlug: 'agent-runs',
  },
  applicationId: {
    className: 'Application',
    labelKeys: ['status', 'applyMethod'],
    resourceSlug: 'applications',
  },
  assignedToProfileId: {
    className: 'CandidateProfile',
    labelKeys: ['name', 'profileKey', 'title'],
    resourceSlug: 'candidate-profiles',
  },
  attachmentId: {
    className: 'Attachment',
    labelKeys: ['title', 'filePath'],
    resourceSlug: 'attachments',
  },
  candidateProfileId: {
    className: 'CandidateProfile',
    labelKeys: ['name', 'profileKey', 'title'],
    resourceSlug: 'candidate-profiles',
  },
  companyId: {
    className: 'Company',
    labelKeys: ['name', 'companyKey'],
    resourceSlug: 'companies',
  },
  companyResearchId: {
    className: 'CompanyResearch',
    labelKeys: ['websiteUrl', 'researchStatus'],
    resourceSlug: 'company-research',
  },
  coverLetterAssetId: {
    className: 'ResumeAsset',
    labelKeys: ['title', 'assetType', 'pdfBasename'],
    resourceSlug: 'resume-assets',
  },
  createdFactId: {
    className: 'Fact',
    editable: false,
    labelKeys: ['textRefined', 'statement'],
    resourceSlug: 'facts',
  },
  decisionId: {
    className: 'Decision',
    labelKeys: ['decision', 'reason'],
    resourceSlug: 'decisions',
  },
  duplicateOfSourceCrawlItemId: {
    className: 'SourceCrawlItem',
    labelKeys: ['title', 'url'],
    resourceSlug: 'source-crawl-items',
  },
  educationId: {
    className: 'Education',
    labelKeys: ['title', 'institution'],
    resourceSlug: 'education',
  },
  evaluationScoreId: {
    className: 'EvaluationScore',
    labelKeys: ['recommendation', 'summary'],
    resourceSlug: 'evaluation-scores',
  },
  experienceId: {
    className: 'Experience',
    labelKeys: ['title', 'experienceKey', 'summary'],
    resourceSlug: 'experience',
  },
  legacyCompanyId: {
    className: 'Company',
    labelKeys: ['name', 'companyKey'],
    resourceSlug: 'companies',
  },
  materialRecordId: {
    editable: false,
    labelKeys: ['title', 'name', 'status'],
  },
  organizationProfileId: {
    className: 'CandidateProfile',
    labelKeys: ['name', 'profileKey', 'title'],
    resourceSlug: 'candidate-profiles',
  },
  opportunityId: {
    className: 'Opportunity',
    labelKeys: ['title', 'companyNameSnapshot'],
    resourceSlug: 'opportunities',
  },
  packetAssetId: {
    className: 'ResumeAsset',
    labelKeys: ['title', 'assetType', 'pdfBasename'],
    resourceSlug: 'resume-assets',
  },
  parentId: {
    className: 'Fact',
    editable: false,
    labelKeys: ['textRefined', 'statement'],
    resourceSlug: 'facts',
  },
  placeId: {
    editable: false,
    labelKeys: ['name', 'label'],
  },
  projectId: {
    className: 'Project',
    labelKeys: ['title', 'projectKey', 'summary'],
    resourceSlug: 'projects',
  },
  resumeAssetId: {
    className: 'ResumeAsset',
    labelKeys: ['title', 'assetType', 'pdfBasename'],
    resourceSlug: 'resume-assets',
  },
  resumeVariantId: {
    className: 'ResumeVariant',
    labelKeys: ['name', 'outputSlug'],
    resourceSlug: 'resume-variants',
  },
  reviewedByProfileId: {
    className: 'CandidateProfile',
    labelKeys: ['name', 'profileKey', 'title'],
    resourceSlug: 'candidate-profiles',
  },
  reviewedByUserId: {
    editable: false,
    labelKeys: ['email', 'name'],
  },
  roleId: {
    className: 'EmploymentRole',
    labelKeys: ['label', 'roleKey'],
    resourceSlug: 'roles',
  },
  sourceAssetId: {
    className: 'ResumeAsset',
    editable: false,
    labelKeys: ['title', 'assetType', 'pdfBasename'],
    resourceSlug: 'resume-assets',
  },
  sourceCrawlId: {
    className: 'SourceCrawl',
    labelKeys: ['query', 'status'],
    resourceSlug: 'source-crawls',
  },
  sourceCrawlItemId: {
    className: 'SourceCrawlItem',
    labelKeys: ['title', 'url'],
    resourceSlug: 'source-crawl-items',
  },
  sourceId: {
    className: 'Source',
    labelKeys: ['name', 'sourceKind'],
    resourceSlug: 'sources',
  },
  sourceVariantId: {
    className: 'ResumeVariant',
    editable: false,
    labelKeys: ['name', 'outputSlug'],
    resourceSlug: 'resume-variants',
  },
  submittedByProfileId: {
    className: 'CandidateProfile',
    labelKeys: ['name', 'profileKey', 'title'],
    resourceSlug: 'candidate-profiles',
  },
  submittedByUserId: {
    editable: false,
    labelKeys: ['email', 'name'],
  },
  tagId: {
    editable: false,
    labelKeys: ['label', 'name'],
  },
  taskId: {
    className: 'Task',
    labelKeys: ['title', 'taskType'],
    resourceSlug: 'tasks',
  },
  targetOpportunityId: {
    className: 'Opportunity',
    labelKeys: ['title', 'companyNameSnapshot'],
    resourceSlug: 'opportunities',
  },
  tailoringConfigId: {
    className: 'ResumeTailoringConfig',
    labelKeys: ['name', 'configSlug'],
    resourceSlug: 'resume-tailoring-configs',
  },
};

export function resourceSlugForClassName(
  className: string,
): string | undefined {
  return resourceSlugByClassName.get(className);
}

const profileReferenceKeys = new Set([
  'actorProfileId',
  'approvedByProfileId',
  'createdByProfileId',
  'deciderProfileId',
  'ownerProfileId',
  'reviewerProfileId',
]);

const userReferenceKeys = new Set([
  'approvedByUserId',
  'createdByUserId',
  'deciderUserId',
  'initiatedByUserId',
  'reviewerUserId',
]);

export function referenceForField(
  field: Pick<ResourceField, 'combo' | 'key' | 'reference'>,
): ReferenceFieldConfig | null {
  if (field.reference) return field.reference;
  if (field.combo) {
    return {
      className: field.combo.className,
      editable: true,
      labelKey: field.combo.labelKey,
      resourceSlug: resourceSlugForClassName(field.combo.className),
    };
  }
  if (referenceByFieldKey[field.key]) return referenceByFieldKey[field.key];
  if (profileReferenceKeys.has(field.key)) {
    return {
      className: 'CandidateProfile',
      labelKeys: ['name', 'profileKey', 'title'],
      resourceSlug: 'candidate-profiles',
    };
  }
  if (userReferenceKeys.has(field.key)) {
    return {
      editable: false,
      labelKeys: ['email', 'name'],
    };
  }
  if (field.key.endsWith('PlaceId')) {
    return {
      editable: false,
      labelKeys: ['name', 'label'],
    };
  }
  return null;
}

export function referenceIsEditable(field: ResourceField): boolean {
  return referenceForField(field)?.editable !== false;
}

export function displayFieldLabel(
  field: Pick<ResourceField, 'combo' | 'key' | 'label' | 'reference'>,
): string {
  if (!referenceForField(field)) return field.label;
  return field.label.replace(/\s+ID$/i, '').replace(/\s+Id$/i, '');
}

export const humanReviewStatuses = [
  'needs_input',
  'maybe',
  'apply',
  'reject',
  'archived',
];
export const resumeModes = ['default', 'generate_tailored', 'custom', 'none'];
export const coverLetterModes = ['none', 'generate', 'custom', 'default'];
export const applyMethods = [
  'company_site',
  'email',
  'recruiter',
  'platform',
  'referral',
  'other',
];

const profileIdField = (key: string, label: string): ResourceField => ({
  key,
  label,
  kind: 'text',
  placeholder: 'smrt-profiles Profile ID',
});

const userIdField = (key: string, label: string): ResourceField => ({
  key,
  label,
  kind: 'text',
  placeholder: 'smrt-users User ID',
});

const tagIdField = (key = 'tagId'): ResourceField => ({
  combo: {
    allowCreate: false,
    className: 'Tag',
    displayKeys: ['context', 'name', 'slug'],
    labelKey: 'name',
    valueKey: 'id',
  },
  key,
  label: 'Tag',
  kind: 'combo',
  required: true,
  placeholder: 'Search existing SMRT tags',
});

const placeIdField = (key = 'placeId', required = true): ResourceField => ({
  key,
  label: 'Place ID',
  kind: 'text',
  required,
  placeholder: 'smrt-places Place ID',
});

const comboField = (
  key: string,
  label: string,
  combo: ComboFieldConfig,
  required = true,
  placeholder?: string,
): ResourceField => ({
  key,
  label,
  kind: 'combo',
  combo,
  placeholder,
  required,
});

export const adminResources: AdminResource[] = [
  {
    slug: 'opportunities',
    className: 'Opportunity',
    label: 'Opportunities',
    singularLabel: 'Opportunity',
    description: 'Found and active roles in the employment-search pipeline.',
    icon: 'briefcase',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'title',
      'humanReviewStatus',
      'humanRating',
      'status',
      'workMode',
      'employmentType',
      'updated_at',
    ],
    fields: [
      { key: 'title', label: 'Title', kind: 'text', required: true },
      { key: 'postingUrl', label: 'Posting URL', kind: 'text', required: true },
      comboField(
        'companyId',
        'Company',
        {
          className: 'Company',
          createKey: 'name',
          labelKey: 'name',
        },
        false,
      ),
      profileIdField('organizationProfileId', 'Organization profile ID'),
      comboField(
        'sourceId',
        'Source',
        {
          allowCreate: false,
          className: 'Source',
          labelKey: 'name',
        },
        false,
        'Search existing source',
      ),
      { key: 'externalId', label: 'External ID', kind: 'text' },
      { key: 'canonicalUrl', label: 'Canonical URL', kind: 'text' },
      {
        key: 'applyMethod',
        label: 'Apply method',
        kind: 'select',
        options: applyMethods,
      },
      { key: 'applyUrl', label: 'Apply URL', kind: 'text' },
      {
        key: 'applyInstructions',
        label: 'Apply instructions',
        kind: 'textarea',
      },
      {
        key: 'status',
        label: 'Status',
        kind: 'select',
        options: pipelineStates,
      },
      {
        key: 'employmentType',
        label: 'Employment type',
        kind: 'select',
        options: [
          'full_time',
          'contract',
          'fractional',
          'advisory',
          'founder',
          'unknown',
        ],
      },
      {
        key: 'seniority',
        label: 'Seniority',
        kind: 'select',
        options: [
          'senior',
          'staff',
          'principal',
          'founding',
          'lead',
          'exec',
          'unknown',
        ],
      },
      {
        key: 'workMode',
        label: 'Work mode',
        kind: 'select',
        options: ['remote', 'hybrid', 'onsite', 'unknown'],
      },
      {
        key: 'locationNotes',
        label: 'Location notes',
        kind: 'textarea',
        rows: 2,
      },
      {
        key: 'locations',
        label: 'Locations',
        kind: 'textarea',
        rows: 3,
        description: agentListFieldDescription,
      },
      {
        key: 'relocationSupported',
        label: 'Relocation supported',
        kind: 'checkbox',
      },
      {
        key: 'visaOrEorPossible',
        label: 'Visa or EOR possible',
        kind: 'checkbox',
      },
      { key: 'salaryMin', label: 'Salary min', kind: 'number' },
      { key: 'salaryMax', label: 'Salary max', kind: 'number' },
      {
        key: 'currency',
        label: 'Currency',
        kind: 'text',
        placeholder: 'CAD, USD',
      },
      { key: 'hourlyMin', label: 'Hourly min', kind: 'number' },
      { key: 'hourlyMax', label: 'Hourly max', kind: 'number' },
      { key: 'equityMinPercent', label: 'Equity min %', kind: 'number' },
      { key: 'equityMaxPercent', label: 'Equity max %', kind: 'number' },
      { key: 'compNotes', label: 'Comp notes', kind: 'textarea' },
      {
        key: 'descriptionRaw',
        label: 'Description',
        kind: 'textarea',
        rows: 6,
      },
      {
        key: 'sourceContentFingerprint',
        label: 'Source content fingerprint',
        kind: 'text',
      },
      {
        key: 'sourceContentVersion',
        label: 'Source content version',
        kind: 'number',
      },
      {
        key: 'sourceContentJson',
        label: 'Source content snapshot',
        kind: 'textarea',
        rows: 6,
      },
      {
        key: 'sourceIntelligenceStatus',
        label: 'Source intelligence status',
        kind: 'select',
        options: [
          'ineligible',
          'pending',
          'queued',
          'duplicate_active',
          'disabled',
          'cap_exhausted',
          'enqueue_failed',
        ],
      },
      {
        key: 'sourceIntelligenceJobId',
        label: 'Source intelligence job ID',
        kind: 'text',
      },
      {
        key: 'requiredSkills',
        label: 'Required skills',
        kind: 'textarea',
        rows: 3,
        description: agentListFieldDescription,
      },
      {
        key: 'preferredSkills',
        label: 'Preferred skills',
        kind: 'textarea',
        rows: 3,
        description: agentListFieldDescription,
      },
      {
        key: 'responsibilities',
        label: 'Responsibilities',
        kind: 'textarea',
        rows: 4,
        description: agentListFieldDescription,
      },
      {
        key: 'qualifications',
        label: 'Qualifications',
        kind: 'textarea',
        rows: 4,
        description: agentListFieldDescription,
      },
      {
        key: 'domainTags',
        label: 'Domain tags',
        kind: 'textarea',
        rows: 3,
        description: agentListFieldDescription,
      },
      {
        key: 'roleTags',
        label: 'Role tags',
        kind: 'textarea',
        rows: 3,
        description: agentListFieldDescription,
      },
      { key: 'greenfieldSignal', label: 'Greenfield signal', kind: 'checkbox' },
      { key: 'founderSignal', label: 'Founder signal', kind: 'checkbox' },
      {
        key: 'freshness',
        label: 'Freshness',
        kind: 'select',
        options: ['fresh', 'known', 'stale', 'closed', 'unknown'],
      },
      {
        key: 'humanRating',
        label: 'User rating',
        kind: 'select',
        options: ['', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        coerce: 'number',
      },
      {
        key: 'humanReviewStatus',
        label: 'User review',
        kind: 'select',
        options: humanReviewStatuses,
      },
      {
        key: 'humanReviewNotes',
        label: 'User review notes',
        kind: 'textarea',
        rows: 3,
      },
      userIdField('reviewedByUserId', 'Reviewed by user ID'),
      profileIdField('reviewedByProfileId', 'Reviewed by profile ID'),
      { key: 'reviewedAt', label: 'Reviewed at', kind: 'datetime' },
      { key: 'firstSeenAt', label: 'First seen', kind: 'datetime' },
      { key: 'lastSeenAt', label: 'Last seen', kind: 'datetime' },
      { key: 'postedAt', label: 'Posted', kind: 'datetime' },
      { key: 'expiresAt', label: 'Expires', kind: 'datetime' },
    ],
  },
  {
    slug: 'company-research',
    className: 'CompanyResearch',
    label: 'Company research',
    singularLabel: 'Company research',
    description:
      'Employment-specific company fit notes linked to organization profiles.',
    icon: 'building',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'organizationProfileId',
      'stage',
      'remotePolicy',
      'researchStatus',
      'updated_at',
    ],
    fields: [
      profileIdField('organizationProfileId', 'Organization profile ID'),
      { key: 'websiteUrl', label: 'Website URL', kind: 'text' },
      { key: 'careersUrl', label: 'Careers URL', kind: 'text' },
      { key: 'linkedinUrl', label: 'LinkedIn URL', kind: 'text' },
      { key: 'crunchbaseUrl', label: 'Crunchbase URL', kind: 'text' },
      { key: 'ycUrl', label: 'YC URL', kind: 'text' },
      {
        key: 'stage',
        label: 'Stage',
        kind: 'select',
        options: [
          'idea',
          'pre_seed',
          'seed',
          'series_a',
          'series_b_plus',
          'public',
          'unknown',
        ],
      },
      {
        key: 'remotePolicy',
        label: 'Remote policy',
        kind: 'select',
        options: ['remote', 'hybrid', 'onsite', 'unknown'],
      },
      placeIdField('hqPlaceId', false),
      { key: 'legacyHqLocation', label: 'Legacy HQ location', kind: 'text' },
      {
        key: 'legacyIndustryTags',
        label: 'Legacy industry tags',
        kind: 'textarea',
        rows: 2,
      },
      {
        key: 'timezoneNotes',
        label: 'Timezone notes',
        kind: 'textarea',
        rows: 2,
      },
      { key: 'fundingNotes', label: 'Funding notes', kind: 'textarea' },
      { key: 'productSummary', label: 'Product summary', kind: 'textarea' },
      { key: 'technicalSummary', label: 'Technical summary', kind: 'textarea' },
      { key: 'whyInteresting', label: 'Why interesting', kind: 'textarea' },
      { key: 'concerns', label: 'Concerns', kind: 'textarea' },
      {
        key: 'researchStatus',
        label: 'Research status',
        kind: 'select',
        options: ['needed', 'partial', 'complete', 'stale'],
      },
      {
        key: 'researchFolderPath',
        label: 'Research folder path',
        kind: 'text',
      },
    ],
  },
  {
    slug: 'sources',
    className: 'Source',
    label: 'Sources',
    singularLabel: 'Source',
    description:
      'Job boards, career pages, feeds, recruiter sources, and search queries.',
    icon: 'rss',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'name',
      'type',
      'accountStatus',
      'isActive',
      'nextCheckAt',
      'updated_at',
    ],
    fields: [
      { key: 'name', label: 'Name', kind: 'text', required: true },
      {
        key: 'sourceRole',
        label: 'Source role',
        kind: 'select',
        options: ['unknown', 'root', 'posting_derived'],
      },
      {
        key: 'parentSourceId',
        label: 'Parent source ID',
        kind: 'text',
        description:
          'Required only for posting-derived sources. Root classification must be an explicit operator decision.',
      },
      {
        key: 'type',
        label: 'Type',
        kind: 'select',
        options: [
          'job_board',
          'company_careers',
          'contract_board',
          'vc_portfolio',
          'recruiter',
          'founder_post',
          'newsletter',
          'search_query',
          'manual',
        ],
      },
      {
        key: 'provider',
        label: 'Provider',
        kind: 'select',
        options: ['unknown', ...sourceProviderIds],
        description:
          'Persisted adapter-attested identity used for provider health.',
      },
      { key: 'url', label: 'URL', kind: 'text' },
      profileIdField('ownerProfileId', 'Owner profile ID'),
      {
        key: 'accountStatus',
        label: 'Account status',
        kind: 'select',
        options: [...accountStatuses],
      },
      {
        key: 'accountNotes',
        label: 'Account notes',
        kind: 'textarea',
        description:
          'Use for setup notes only. Do not paste passwords, tokens, cookies, or recovery codes.',
      },
      {
        key: 'loginIdentity',
        label: 'Login identity',
        kind: 'text',
        description:
          'Username, email, or account handle only. Store credentials in Warden.',
      },
      {
        key: 'accountOwnerRole',
        label: 'Account owner',
        kind: 'select',
        options: taskAssigneeRoles,
      },
      {
        key: 'wardenReference',
        label: 'Credential secret reference',
        kind: 'text',
        description:
          'Non-secret Warden item or folder reference. Never store the secret value here.',
        placeholder: 'Warden item/folder reference',
      },
      { key: 'searchQuery', label: 'Search query', kind: 'textarea' },
      {
        key: 'refreshCadence',
        label: 'Refresh cadence',
        kind: 'select',
        options: ['daily', 'weekly', 'monthly', 'ad_hoc'],
      },
      { key: 'lastCheckedAt', label: 'Last checked', kind: 'datetime' },
      { key: 'nextCheckAt', label: 'Next check', kind: 'datetime' },
      {
        key: 'isActive',
        label: 'Active',
        kind: 'checkbox',
        defaultValue: false,
      },
    ],
  },
  {
    slug: 'source-crawls',
    className: 'SourceCrawl',
    label: 'Source crawls',
    singularLabel: 'Source crawl',
    description:
      'Each source crawl/search attempt with query, tags, filters, and result counts.',
    icon: 'search',
    orderBy: 'startedAt DESC',
    tableColumns: [
      'sourceId',
      'crawlType',
      'status',
      'resultCount',
      'recommendedCount',
      'startedAt',
    ],
    fields: [
      { key: 'sourceId', label: 'Source ID', kind: 'text', required: true },
      {
        key: 'crawlType',
        label: 'Crawl type',
        kind: 'select',
        options: ['api', 'browser', 'spider', 'manual', 'search_query', 'feed'],
      },
      {
        key: 'status',
        label: 'Status',
        kind: 'select',
        options: [
          'queued',
          'running',
          'completed',
          'completed_with_errors',
          'failed',
          'timed_out',
          'needs_login',
          'rate_limited',
        ],
      },
      profileIdField('actorProfileId', 'Actor profile ID'),
      userIdField('initiatedByUserId', 'Initiated by user ID'),
      { key: 'agentRunId', label: 'Agent run ID', kind: 'text' },
      { key: 'jobId', label: 'Job ID', kind: 'text' },
      { key: 'query', label: 'Query', kind: 'textarea', rows: 3 },
      { key: 'tagsJson', label: 'Tags JSON', kind: 'textarea', rows: 3 },
      { key: 'filtersJson', label: 'Filters JSON', kind: 'textarea', rows: 4 },
      {
        key: 'preferenceSnapshotJson',
        label: 'Preference snapshot JSON',
        kind: 'textarea',
        rows: 4,
      },
      {
        key: 'integrationMethod',
        label: 'Integration method',
        kind: 'select',
        options: [
          'api',
          'browser',
          'spider',
          'rss',
          'manual',
          'search_query',
          'unknown',
        ],
      },
      { key: 'resultCount', label: 'Result count', kind: 'number' },
      {
        key: 'newOpportunityCount',
        label: 'New opportunities',
        kind: 'number',
      },
      { key: 'duplicateCount', label: 'Duplicates', kind: 'number' },
      { key: 'reusedCount', label: 'Reused opportunities', kind: 'number' },
      { key: 'relistedCount', label: 'Relistings', kind: 'number' },
      { key: 'recommendedCount', label: 'Recommended', kind: 'number' },
      { key: 'skippedCount', label: 'Skipped', kind: 'number' },
      {
        key: 'failedPersistenceCount',
        label: 'Persistence failures',
        kind: 'number',
      },
      { key: 'attemptCount', label: 'Candidate attempts', kind: 'number' },
      { key: 'terminalCount', label: 'Terminal attempts', kind: 'number' },
      { key: 'pendingCount', label: 'Pending attempts', kind: 'number' },
      {
        key: 'intelligenceEnqueueCap',
        label: 'Intelligence enqueue cap',
        kind: 'number',
      },
      {
        key: 'intelligenceEnqueuedCount',
        label: 'Intelligence jobs queued',
        kind: 'number',
      },
      {
        key: 'intelligenceDuplicateCount',
        label: 'Intelligence jobs deduplicated',
        kind: 'number',
      },
      {
        key: 'intelligenceSkippedCount',
        label: 'Intelligence jobs skipped',
        kind: 'number',
      },
      { key: 'error', label: 'Error', kind: 'textarea', rows: 3 },
      { key: 'notes', label: 'Notes', kind: 'textarea', rows: 4 },
      { key: 'rawOutputPath', label: 'Raw output path', kind: 'text' },
      { key: 'startedAt', label: 'Started at', kind: 'datetime' },
      { key: 'finishedAt', label: 'Finished at', kind: 'datetime' },
    ],
  },
  {
    slug: 'source-crawl-items',
    className: 'SourceCrawlItem',
    label: 'Source crawl items',
    singularLabel: 'Source crawl item',
    description: 'Per-posting outcomes produced by a source crawl.',
    icon: 'list',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'sourceCrawlId',
      'outcome',
      'status',
      'reconciliationStatus',
      'title',
      'companyName',
      'opportunityId',
      'updated_at',
    ],
    fields: [
      {
        key: 'sourceCrawlId',
        label: 'Source crawl ID',
        kind: 'text',
        required: true,
      },
      { key: 'attemptKey', label: 'Attempt key', kind: 'text' },
      {
        key: 'outcome',
        label: 'Terminal outcome',
        kind: 'select',
        options: [
          'pending',
          'created',
          'reused',
          'relisted',
          'duplicate',
          'skipped',
          'failed_persistence',
        ],
      },
      { key: 'terminalAt', label: 'Terminal at', kind: 'datetime' },
      { key: 'opportunityId', label: 'Opportunity ID', kind: 'text' },
      {
        key: 'duplicateOfSourceCrawlItemId',
        label: 'Duplicate of source crawl item ID',
        kind: 'text',
      },
      {
        key: 'reconciliationStatus',
        label: 'Reconciliation status',
        kind: 'select',
        options: [
          'unmatched',
          'matched_existing',
          'created_opportunity',
          'duplicate',
          'ambiguous',
          'ignored',
        ],
      },
      { key: 'reconciliationKey', label: 'Reconciliation key', kind: 'text' },
      {
        key: 'matchStrategy',
        label: 'Match strategy',
        kind: 'select',
        options: [
          'none',
          'canonical_url',
          'posting_url',
          'external_id',
          'title_company',
          'manual',
        ],
      },
      { key: 'matchConfidence', label: 'Match confidence', kind: 'number' },
      {
        key: 'reconciliationNotes',
        label: 'Reconciliation notes',
        kind: 'textarea',
        rows: 3,
      },
      { key: 'externalId', label: 'External ID', kind: 'text' },
      { key: 'postingUrl', label: 'Posting URL', kind: 'text' },
      { key: 'canonicalUrl', label: 'Canonical URL', kind: 'text' },
      { key: 'title', label: 'Title', kind: 'text' },
      { key: 'companyName', label: 'Company name', kind: 'text' },
      {
        key: 'status',
        label: 'Status',
        kind: 'select',
        options: [
          'seen',
          'new',
          'updated',
          'created_opportunity',
          'updated_opportunity',
          'duplicate',
          'rejected_no_posting_url',
          'skipped_not_relevant',
          'skipped_relist_unresolved',
          'skipped',
          'recommended',
          'created',
        ],
      },
      {
        key: 'contentFingerprint',
        label: 'Content fingerprint',
        kind: 'text',
      },
      { key: 'contentVersion', label: 'Content version', kind: 'number' },
      {
        key: 'intelligenceEnqueueStatus',
        label: 'Intelligence enqueue status',
        kind: 'select',
        options: [
          'ineligible',
          'pending',
          'queued',
          'duplicate_active',
          'unchanged',
          'disabled',
          'cap_exhausted',
          'enqueue_failed',
        ],
      },
      {
        key: 'intelligenceJobId',
        label: 'Intelligence job ID',
        kind: 'text',
      },
      { key: 'reason', label: 'Reason', kind: 'textarea', rows: 3 },
      { key: 'rawJson', label: 'Raw JSON', kind: 'textarea', rows: 5 },
    ],
  },
  {
    slug: 'applications',
    className: 'Application',
    label: 'Applications',
    singularLabel: 'Application',
    description:
      'Application-stage records requiring explicit user approval before submission.',
    icon: 'send',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'opportunityId',
      'sourceCrawlItemId',
      'status',
      'approvedAt',
      'submittedAt',
      'updated_at',
    ],
    fields: [
      {
        key: 'opportunityId',
        label: 'Opportunity ID',
        kind: 'text',
        required: true,
      },
      { key: 'sourceCrawlId', label: 'Source crawl ID', kind: 'text' },
      { key: 'sourceCrawlItemId', label: 'Source crawl item ID', kind: 'text' },
      { key: 'evaluationScoreId', label: 'Evaluation score ID', kind: 'text' },
      { key: 'decisionId', label: 'Decision ID', kind: 'text' },
      {
        key: 'status',
        label: 'Status',
        kind: 'select',
        options: [...applicationStatuses],
      },
      {
        key: 'applyMethod',
        label: 'Apply method',
        kind: 'select',
        options: applyMethods,
      },
      {
        key: 'resumeMode',
        label: 'Resume mode',
        kind: 'select',
        options: resumeModes,
      },
      {
        key: 'coverLetterMode',
        label: 'Cover letter mode',
        kind: 'select',
        options: coverLetterModes,
      },
      {
        key: 'applicationInstructions',
        label: 'Application instructions',
        kind: 'textarea',
        rows: 3,
      },
      {
        key: 'requiredAnswers',
        label: 'Required answers',
        kind: 'textarea',
        rows: 3,
      },
      { key: 'dueAt', label: 'Due at', kind: 'datetime' },
      userIdField('approvedByUserId', 'Approved by user ID'),
      profileIdField('approvedByProfileId', 'Approved by profile ID'),
      { key: 'approvedAt', label: 'Approved at', kind: 'datetime' },
      {
        key: 'approvalNotes',
        label: 'Approval notes',
        kind: 'textarea',
        rows: 3,
      },
      {
        key: 'approvalScope',
        label: 'Approval scope',
        kind: 'textarea',
        rows: 2,
      },
      { key: 'applicationUrl', label: 'Application URL', kind: 'text' },
      {
        key: 'accountStatus',
        label: 'Account status',
        kind: 'select',
        options: [...accountStatuses],
      },
      {
        key: 'accountLoginIdentity',
        label: 'Account login identity',
        kind: 'text',
      },
      {
        key: 'accountNotes',
        label: 'Account notes',
        kind: 'textarea',
        rows: 3,
      },
      {
        key: 'wardenReference',
        label: 'Warden reference',
        kind: 'text',
        placeholder: 'Non-secret Warden item/folder reference',
      },
      { key: 'resumeAssetId', label: 'Resume asset ID', kind: 'text' },
      { key: 'resumeVariantId', label: 'Resume variant ID', kind: 'text' },
      {
        key: 'coverLetterAssetId',
        label: 'Cover letter asset ID',
        kind: 'text',
      },
      { key: 'packetAssetId', label: 'Packet asset ID', kind: 'text' },
      { key: 'notes', label: 'Notes', kind: 'textarea', rows: 4 },
    ],
  },
  {
    slug: 'application-material-comments',
    className: 'ApplicationMaterialComment',
    label: 'Application material comments',
    singularLabel: 'material comment',
    description:
      'Per-application review comments attached to generated application materials.',
    icon: 'message-square',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'applicationId',
      'materialType',
      'status',
      'reviewerProfileId',
      'updated_at',
    ],
    fields: [
      {
        key: 'applicationId',
        label: 'Application',
        kind: 'text',
        required: true,
      },
      {
        key: 'materialType',
        label: 'Material',
        kind: 'select',
        options: [
          'packet',
          'resume',
          'resume_variant',
          'cover_letter',
          'answers',
        ],
      },
      {
        key: 'materialRecordType',
        label: 'Material record type',
        kind: 'select',
        options: ['ResumeAsset', 'ResumeVariant', 'Application'],
      },
      {
        key: 'materialRecordId',
        label: 'Material record',
        kind: 'text',
      },
      { key: 'body', label: 'Comment', kind: 'textarea', rows: 4 },
      {
        key: 'status',
        label: 'Status',
        kind: 'select',
        options: ['open', 'addressed', 'resolved', 'archived'],
      },
      userIdField('reviewerUserId', 'Reviewer user'),
      profileIdField('reviewerProfileId', 'Reviewer profile'),
      { key: 'resolvedAt', label: 'Resolved at', kind: 'datetime' },
    ],
  },
  {
    slug: 'fact-intakes',
    className: 'FactIntake',
    label: 'Notes',
    singularLabel: 'note',
    description:
      'Raw snippets, stories, and brainstorms queued for fact extraction.',
    icon: 'file-text',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'sourceKind',
      'targetEntityType',
      'status',
      'extractedAt',
      'updated_at',
    ],
    fields: [
      {
        key: 'sourceKind',
        label: 'Source kind',
        kind: 'select',
        options: [
          'story',
          'snippet',
          'brainstorm',
          'resume',
          'opportunity',
          'company',
          'other',
        ],
      },
      { key: 'targetEntityType', label: 'Target entity type', kind: 'text' },
      { key: 'targetEntityId', label: 'Target entity ID', kind: 'text' },
      {
        key: 'status',
        label: 'Status',
        kind: 'select',
        options: ['draft', 'extracted', 'reviewed', 'archived'],
      },
      {
        key: 'rawText',
        label: 'Raw text',
        kind: 'textarea',
        rows: 8,
        required: true,
      },
      { key: 'intakeContext', label: 'Context', kind: 'textarea', rows: 3 },
      {
        key: 'extractedCandidatesJson',
        label: 'Extracted candidates JSON',
        kind: 'textarea',
        rows: 6,
      },
      userIdField('createdByUserId', 'Created by user ID'),
      profileIdField('createdByProfileId', 'Created by profile ID'),
      { key: 'extractedAt', label: 'Extracted at', kind: 'datetime' },
      { key: 'notes', label: 'Notes', kind: 'textarea', rows: 3 },
    ],
  },
  {
    slug: 'fact-candidates',
    className: 'FactCandidate',
    label: 'Review queue',
    singularLabel: 'review item',
    description:
      'Extracted candidate facts awaiting review before becoming active facts.',
    icon: 'check-square',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'statement',
      'reviewStatus',
      'factType',
      'targetEntityType',
      'updated_at',
    ],
    fields: [
      { key: 'factIntakeId', label: 'Fact intake ID', kind: 'text' },
      { key: 'targetEntityType', label: 'Target entity type', kind: 'text' },
      { key: 'targetEntityId', label: 'Target entity ID', kind: 'text' },
      {
        key: 'statement',
        label: 'Statement',
        kind: 'textarea',
        rows: 4,
        required: true,
      },
      {
        key: 'editedStatement',
        label: 'Edited statement',
        kind: 'textarea',
        rows: 4,
      },
      {
        key: 'factType',
        label: 'Fact type',
        kind: 'select',
        options: [
          'assertion',
          'observation',
          'measurement',
          'definition',
          'relationship',
          'event',
          'opinion',
          'prediction',
        ],
      },
      {
        key: 'sourceExcerpt',
        label: 'Source excerpt',
        kind: 'textarea',
        rows: 3,
      },
      { key: 'confidence', label: 'Confidence', kind: 'number' },
      {
        key: 'reviewStatus',
        label: 'Review status',
        kind: 'select',
        options: ['pending', 'accepted', 'rejected', 'needs_edit'],
      },
      { key: 'createdFactId', label: 'Created fact ID', kind: 'text' },
      userIdField('reviewedByUserId', 'Reviewed by user ID'),
      profileIdField('reviewedByProfileId', 'Reviewed by profile ID'),
      { key: 'reviewedAt', label: 'Reviewed at', kind: 'datetime' },
      { key: 'notes', label: 'Notes', kind: 'textarea', rows: 3 },
    ],
  },
  {
    slug: 'facts',
    className: 'Fact',
    label: 'Facts',
    singularLabel: 'fact',
    description: 'Reviewed knowledge facts with confidence and provenance.',
    icon: 'file-text',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'textRefined',
      'type',
      'domain',
      'status',
      'confidence',
      'updated_at',
    ],
    fields: [
      {
        key: 'textRefined',
        label: 'Refined text',
        kind: 'textarea',
        rows: 4,
        required: true,
      },
      { key: 'textRaw', label: 'Raw text', kind: 'textarea', rows: 4 },
      {
        key: 'type',
        label: 'Type',
        kind: 'select',
        options: [
          'assertion',
          'observation',
          'measurement',
          'definition',
          'relationship',
          'event',
          'opinion',
          'prediction',
        ],
      },
      {
        key: 'status',
        label: 'Status',
        kind: 'select',
        options: [
          'pending',
          'active',
          'disputed',
          'superseded',
          'archived',
          'retracted',
        ],
      },
      { key: 'domain', label: 'Domain', kind: 'text' },
      { key: 'parentId', label: 'Parent fact ID', kind: 'text' },
      { key: 'evolutionType', label: 'Evolution type', kind: 'text' },
      { key: 'sourceCount', label: 'Source count', kind: 'number' },
      { key: 'confidence', label: 'Confidence', kind: 'number' },
      { key: 'metadata', label: 'Metadata JSON', kind: 'textarea', rows: 5 },
    ],
  },
  {
    slug: 'tasks',
    className: 'Task',
    label: 'Tasks',
    singularLabel: 'Task',
    description:
      'Review work, signup needs, company research, and application prep.',
    icon: 'check-square',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'title',
      'assigneeRole',
      'kanbanColumn',
      'status',
      'taskType',
      'dueAt',
      'updated_at',
    ],
    fields: [
      { key: 'title', label: 'Title', kind: 'text', required: true },
      { key: 'description', label: 'Description', kind: 'textarea', rows: 4 },
      {
        key: 'status',
        label: 'Status',
        kind: 'select',
        options: [...taskStatuses],
      },
      {
        key: 'kanbanColumn',
        label: 'Kanban column',
        kind: 'select',
        options: [...taskKanbanColumns],
      },
      {
        key: 'assigneeRole',
        label: 'Assignee',
        kind: 'select',
        options: [...taskAssigneeRoles],
      },
      {
        key: 'blockerReason',
        label: 'Blocker reason',
        kind: 'textarea',
        rows: 3,
      },
      {
        key: 'blockerOwnerRole',
        label: 'Blocker owner',
        kind: 'select',
        options: ['', ...taskAssigneeRoles],
      },
      {
        key: 'taskType',
        label: 'Task type',
        kind: 'select',
        options: [...taskTypes],
      },
      { key: 'opportunityId', label: 'Opportunity ID', kind: 'text' },
      { key: 'applicationId', label: 'Application ID', kind: 'text' },
      { key: 'decisionId', label: 'Decision ID', kind: 'text' },
      { key: 'companyId', label: 'Company ID', kind: 'text' },
      profileIdField('organizationProfileId', 'Organization profile ID'),
      { key: 'sourceId', label: 'Source ID', kind: 'text' },
      {
        key: 'artifactRefsJson',
        label: 'Artifact refs JSON',
        kind: 'textarea',
        rows: 3,
        description: agentJsonFieldDescription,
      },
      { key: 'externalTaskId', label: 'External task ID', kind: 'text' },
      { key: 'dueAt', label: 'Due at', kind: 'datetime' },
      { key: 'completedAt', label: 'Completed at', kind: 'datetime' },
      profileIdField('createdByProfileId', 'Created by profile ID'),
      profileIdField('assignedToProfileId', 'Assigned to profile ID'),
      {
        key: 'createdBy',
        label: 'Created by',
        kind: 'select',
        options: taskAssigneeRoles,
      },
    ],
  },
  {
    slug: 'decisions',
    className: 'Decision',
    label: 'Decisions',
    singularLabel: 'Decision',
    description: 'Accept, reject, defer, elevate, and archive rationale.',
    icon: 'gavel',
    orderBy: 'created_at DESC',
    tableColumns: [
      'decision',
      'deciderProfileId',
      'opportunityId',
      'sourceCrawlItemId',
      'newStatus',
      'created_at',
    ],
    fields: [
      {
        key: 'opportunityId',
        label: 'Opportunity ID',
        kind: 'text',
        required: true,
      },
      { key: 'applicationId', label: 'Application ID', kind: 'text' },
      { key: 'taskId', label: 'Task ID', kind: 'text' },
      { key: 'sourceCrawlId', label: 'Source crawl ID', kind: 'text' },
      { key: 'sourceCrawlItemId', label: 'Source crawl item ID', kind: 'text' },
      { key: 'evaluationScoreId', label: 'Evaluation score ID', kind: 'text' },
      { key: 'agentRunId', label: 'Agent run ID', kind: 'text' },
      profileIdField('deciderProfileId', 'Decider profile ID'),
      userIdField('deciderUserId', 'Decider user ID'),
      {
        key: 'decision',
        label: 'Decision',
        kind: 'select',
        options: [...recommendationDecisions, 'elevate'],
      },
      { key: 'reason', label: 'Reason', kind: 'textarea', rows: 4 },
      {
        key: 'previousStatus',
        label: 'Previous status',
        kind: 'select',
        options: pipelineStates,
      },
      {
        key: 'newStatus',
        label: 'New status',
        kind: 'select',
        options: pipelineStates,
      },
      {
        key: 'decisionTags',
        label: 'Decision tags',
        kind: 'textarea',
        rows: 3,
        description: agentListFieldDescription,
      },
    ],
  },
  {
    slug: 'agent-runs',
    className: 'AgentRun',
    label: 'Agent runs',
    singularLabel: 'Agent run',
    description: 'Agent activity and outputs linked to workflow records.',
    icon: 'bot',
    orderBy: 'updated_at DESC',
    rowAction: 'none',
    tableColumns: [
      'runType',
      'status',
      'opportunityId',
      'sourceId',
      'updated_at',
    ],
    fields: [
      {
        key: 'runType',
        label: 'Run type',
        kind: 'select',
        options: [
          'source_scout',
          'source_crawl',
          'opportunity_scout',
          'company_research',
          'application_packet',
          'application_submission',
          'scoring',
          'opportunity_llm_extract',
          'opportunity_llm_score',
          'opportunity_llm_evidence',
          'opportunity_llm_plan',
          'opportunity_llm_research',
          'opportunity_llm_quality',
          'resume_tailor',
          'other',
        ],
      },
      {
        key: 'status',
        label: 'Status',
        kind: 'select',
        options: ['queued', 'running', 'succeeded', 'failed', 'canceled'],
      },
      profileIdField('actorProfileId', 'Actor profile ID'),
      userIdField('initiatedByUserId', 'Initiated by user ID'),
      { key: 'opportunityId', label: 'Opportunity ID', kind: 'text' },
      { key: 'applicationId', label: 'Application ID', kind: 'text' },
      { key: 'taskId', label: 'Task ID', kind: 'text' },
      profileIdField('organizationProfileId', 'Organization profile ID'),
      { key: 'sourceId', label: 'Source ID', kind: 'text' },
      {
        key: 'externalActionType',
        label: 'External action type',
        kind: 'text',
      },
      {
        key: 'approvalSnapshotJson',
        label: 'Approval snapshot JSON',
        kind: 'textarea',
        rows: 4,
      },
      { key: 'inputJson', label: 'Input JSON', kind: 'textarea', rows: 5 },
      { key: 'outputJson', label: 'Output JSON', kind: 'textarea', rows: 5 },
      { key: 'error', label: 'Error', kind: 'textarea', rows: 4 },
      { key: 'startedAt', label: 'Started at', kind: 'datetime' },
      { key: 'finishedAt', label: 'Finished at', kind: 'datetime' },
    ],
  },
  {
    slug: 'evaluation-scores',
    className: 'EvaluationScore',
    label: 'Evaluation scores',
    singularLabel: 'Evaluation score',
    description:
      'Recommendation scores and rationale produced by agents or humans.',
    icon: 'bar-chart',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'opportunityId',
      'sourceCrawlItemId',
      'score',
      'recommendation',
      'updated_at',
    ],
    fields: [
      {
        key: 'opportunityId',
        label: 'Opportunity ID',
        kind: 'text',
        required: true,
      },
      { key: 'sourceCrawlId', label: 'Source crawl ID', kind: 'text' },
      { key: 'sourceCrawlItemId', label: 'Source crawl item ID', kind: 'text' },
      { key: 'sourceId', label: 'Source ID', kind: 'text' },
      {
        key: 'sourceContentFingerprint',
        label: 'Source content fingerprint',
        kind: 'text',
      },
      {
        key: 'sourceContentVersion',
        label: 'Source content version',
        kind: 'number',
      },
      { key: 'agentRunId', label: 'Agent run ID', kind: 'text' },
      { key: 'score', label: 'Score', kind: 'number' },
      {
        key: 'recommendation',
        label: 'Recommendation',
        kind: 'select',
        options: [
          'recommend',
          'maybe',
          'needs_research',
          'reject',
          'skip',
          'unknown',
        ],
      },
      { key: 'summary', label: 'Summary', kind: 'textarea', rows: 4 },
      { key: 'reasonJson', label: 'Reason JSON', kind: 'textarea', rows: 5 },
      profileIdField('createdByProfileId', 'Created by profile ID'),
    ],
  },
  {
    slug: 'resume-assets',
    className: 'ResumeAsset',
    label: 'Assets',
    singularLabel: 'asset',
    description: 'Source and generated resume/profile artifacts for tailoring.',
    icon: 'file-text',
    orderBy: 'updated_at DESC',
    tableColumns: ['title', 'status', 'isPublished', 'pdfPath', 'updated_at'],
    fields: [
      { key: 'applicationId', label: 'Application', kind: 'text' },
      { key: 'sourceAssetId', label: 'Source asset', kind: 'text' },
      profileIdField('candidateProfileId', 'Candidate profile ID'),
      {
        key: 'assetType',
        label: 'Asset type',
        kind: 'select',
        options: [
          'resume',
          'cover_letter',
          'application_packet',
          'profile',
          'portfolio',
          'other',
        ],
      },
      {
        key: 'status',
        label: 'Status',
        kind: 'select',
        options: ['generated', 'published', 'failed', 'archived'],
      },
      { key: 'title', label: 'Title', kind: 'text', required: true },
      { key: 'sourcePath', label: 'Source path', kind: 'text' },
      { key: 'generatedPath', label: 'Generated path', kind: 'text' },
      { key: 'markdownPath', label: 'Markdown path', kind: 'text' },
      { key: 'textPath', label: 'Text path', kind: 'text' },
      { key: 'htmlPath', label: 'HTML path', kind: 'text' },
      { key: 'pdfPath', label: 'PDF path', kind: 'text' },
      { key: 'pdfBasename', label: 'PDF basename', kind: 'text' },
      { key: 'outputSlug', label: 'Output slug', kind: 'text' },
      { key: 'tailoringId', label: 'Tailoring config ID', kind: 'text' },
      { key: 'isPublished', label: 'Published', kind: 'checkbox' },
      { key: 'generatedAt', label: 'Generated at', kind: 'datetime' },
      { key: 'publishedAt', label: 'Published at', kind: 'datetime' },
      {
        key: 'targetOpportunityId',
        label: 'Target opportunity ID',
        kind: 'text',
      },
      { key: 'notes', label: 'Notes', kind: 'textarea', rows: 4 },
    ],
  },
  {
    slug: 'resume-variants',
    className: 'ResumeVariant',
    label: 'Resume variants',
    singularLabel: 'resume variant',
    description:
      'Opportunity/company-specific resume tailoring workflow records.',
    icon: 'sliders',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'name',
      'status',
      'opportunityId',
      'companyId',
      'pdfPath',
      'updated_at',
    ],
    fields: [
      { key: 'applicationId', label: 'Application ID', kind: 'text' },
      { key: 'sourceVariantId', label: 'Source variant ID', kind: 'text' },
      {
        key: 'opportunityId',
        label: 'Opportunity ID',
        kind: 'text',
        required: true,
      },
      { key: 'companyId', label: 'Company ID', kind: 'text' },
      profileIdField('candidateProfileId', 'Candidate profile ID'),
      { key: 'resumeAssetId', label: 'Resume asset ID', kind: 'text' },
      {
        key: 'tailoringConfigId',
        label: 'Tailoring config ID',
        kind: 'text',
      },
      {
        key: 'tailoringConfigPath',
        label: 'Tailoring config path',
        kind: 'text',
      },
      {
        key: 'status',
        label: 'Status',
        kind: 'select',
        options: ['draft', 'generated', 'reviewed', 'archived'],
      },
      { key: 'name', label: 'Name', kind: 'text', required: true },
      { key: 'outputSlug', label: 'Output slug', kind: 'text' },
      { key: 'titleOverride', label: 'Title override', kind: 'text' },
      {
        key: 'summaryOverride',
        label: 'Summary override',
        kind: 'textarea',
        rows: 4,
      },
      {
        key: 'emphasizeTags',
        label: 'Emphasize tags',
        kind: 'textarea',
        rows: 3,
        description: agentListFieldDescription,
      },
      {
        key: 'excludeTags',
        label: 'Exclude tags',
        kind: 'textarea',
        rows: 3,
        description: agentListFieldDescription,
      },
      {
        key: 'includePositionIds',
        label: 'Include position IDs',
        kind: 'textarea',
        rows: 3,
        description: agentListFieldDescription,
      },
      {
        key: 'excludePositionIds',
        label: 'Exclude position IDs',
        kind: 'textarea',
        rows: 3,
        description: agentListFieldDescription,
      },
      { key: 'generatedPath', label: 'Generated path', kind: 'text' },
      { key: 'markdownPath', label: 'Markdown path', kind: 'text' },
      { key: 'textPath', label: 'Text path', kind: 'text' },
      { key: 'htmlPath', label: 'HTML path', kind: 'text' },
      { key: 'pdfPath', label: 'PDF path', kind: 'text' },
      { key: 'generatedAt', label: 'Generated at', kind: 'datetime' },
      { key: 'notes', label: 'Notes', kind: 'textarea', rows: 4 },
    ],
  },
  {
    slug: 'opportunity-companies',
    className: 'OpportunityCompany',
    label: 'Opportunity companies',
    singularLabel: 'Opportunity company',
    description: 'Company and organization relationships for each opportunity.',
    icon: 'building',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'opportunityId',
      'companyRole',
      'organizationProfileId',
      'isPrimary',
      'updated_at',
    ],
    fields: [
      {
        key: 'opportunityId',
        label: 'Opportunity ID',
        kind: 'text',
        required: true,
      },
      profileIdField('organizationProfileId', 'Organization profile ID'),
      { key: 'companyResearchId', label: 'Company research ID', kind: 'text' },
      { key: 'legacyCompanyId', label: 'Legacy company ID', kind: 'text' },
      {
        key: 'companyRole',
        label: 'Company role',
        kind: 'select',
        options: [
          'employer',
          'client',
          'recruiter_agency',
          'staffing_vendor',
          'parent',
          'subsidiary',
          'source_company',
          'unknown',
        ],
      },
      { key: 'isPrimary', label: 'Primary', kind: 'checkbox' },
      { key: 'sourceCrawlItemId', label: 'Source crawl item ID', kind: 'text' },
      { key: 'notes', label: 'Notes', kind: 'textarea', rows: 3 },
    ],
  },
  {
    slug: 'candidate-profiles',
    className: 'CandidateProfile',
    label: 'Profiles',
    singularLabel: 'profile',
    description:
      'Reusable identity, contact, and profile-summary facts used to seed ATS application forms. Contact details stay private.',
    icon: 'file-text',
    orderBy: 'profileKey ASC',
    tableColumns: [
      'profileKey',
      'name',
      'title',
      'email',
      'active',
      'isDefault',
      'updated_at',
    ],
    fields: [
      {
        key: 'profileKey',
        label: 'Profile key',
        kind: 'text',
        required: true,
        defaultValue: 'default',
      },
      { key: 'name', label: 'Name', kind: 'text', required: true },
      { key: 'firstName', label: 'First name', kind: 'text' },
      { key: 'lastName', label: 'Last name', kind: 'text' },
      { key: 'title', label: 'Title', kind: 'text', required: true },
      { key: 'email', label: 'Email', kind: 'text', required: true },
      {
        key: 'phone',
        label: 'Phone (private)',
        kind: 'text',
      },
      {
        key: 'location',
        label: 'Location',
        kind: 'text',
      },
      {
        key: 'linkedinUrl',
        label: 'LinkedIn URL',
        kind: 'text',
      },
      {
        key: 'githubUrl',
        label: 'GitHub URL',
        kind: 'text',
      },
      {
        key: 'workAuthorization',
        label: 'Work authorization preference',
        kind: 'textarea',
        rows: 2,
      },
      {
        key: 'summary',
        label: 'Summary',
        kind: 'textarea',
        rows: 6,
        required: true,
      },
      { key: 'active', label: 'Active', kind: 'checkbox', defaultValue: true },
      {
        key: 'isDefault',
        label: 'Default',
        kind: 'checkbox',
        defaultValue: false,
      },
    ],
  },
  {
    slug: 'candidate-profile-links',
    className: 'CandidateProfileLink',
    label: 'Profile links',
    singularLabel: 'profile link',
    description:
      'Contact and profile links shown in profile and resume headers.',
    icon: 'rss',
    orderBy: 'sortOrder ASC',
    tableColumns: ['profileKey', 'label', 'href', 'sortOrder', 'updated_at'],
    fields: [
      {
        key: 'profileKey',
        label: 'Profile key',
        kind: 'text',
        required: true,
        defaultValue: 'default',
      },
      { key: 'label', label: 'Label', kind: 'text', required: true },
      { key: 'href', label: 'URL', kind: 'text', required: true },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'companies',
    className: 'Company',
    label: 'Companies',
    singularLabel: 'company',
    description:
      'Organizations used by experience, opportunities, and research.',
    icon: 'building',
    orderBy: 'name ASC',
    tableColumns: ['name', 'websiteUrl', 'stage', 'remotePolicy', 'updated_at'],
    fields: [
      { key: 'companyKey', label: 'Company key', kind: 'text' },
      { key: 'name', label: 'Name', kind: 'text', required: true },
      { key: 'websiteUrl', label: 'Website URL', kind: 'text' },
      { key: 'careersUrl', label: 'Careers URL', kind: 'text' },
      { key: 'linkedinUrl', label: 'LinkedIn URL', kind: 'text' },
      { key: 'crunchbaseUrl', label: 'Crunchbase URL', kind: 'text' },
      { key: 'ycUrl', label: 'YC URL', kind: 'text' },
      {
        key: 'stage',
        label: 'Stage',
        kind: 'select',
        options: [
          'idea',
          'pre_seed',
          'seed',
          'series_a',
          'series_b_plus',
          'public',
          'unknown',
        ],
      },
      {
        key: 'industryTags',
        label: 'Legacy industry tags',
        kind: 'textarea',
        rows: 2,
        description: agentListFieldDescription,
      },
      { key: 'hqLocation', label: 'Legacy HQ location', kind: 'text' },
      {
        key: 'remotePolicy',
        label: 'Remote policy',
        kind: 'select',
        options: ['remote', 'hybrid', 'onsite', 'unknown'],
      },
      {
        key: 'timezoneNotes',
        label: 'Timezone notes',
        kind: 'textarea',
        rows: 2,
      },
      { key: 'fundingNotes', label: 'Funding notes', kind: 'textarea' },
      { key: 'productSummary', label: 'Product summary', kind: 'textarea' },
      { key: 'technicalSummary', label: 'Technical summary', kind: 'textarea' },
      { key: 'whyInteresting', label: 'Why interesting', kind: 'textarea' },
      { key: 'concerns', label: 'Concerns', kind: 'textarea' },
      {
        key: 'researchStatus',
        label: 'Research status',
        kind: 'select',
        options: ['needed', 'partial', 'complete', 'stale'],
      },
      {
        key: 'researchFolderPath',
        label: 'Research folder path',
        kind: 'text',
      },
    ],
  },
  {
    slug: 'roles',
    className: 'EmploymentRole',
    label: 'Roles',
    singularLabel: 'role',
    description: 'Shared role taxonomy used by experience and opportunities.',
    icon: 'briefcase',
    orderBy: 'label ASC',
    tableColumns: ['label', 'roleSlug', 'sortOrder', 'updated_at'],
    fields: [
      { key: 'roleKey', label: 'Role key', kind: 'text' },
      { key: 'roleSlug', label: 'Slug', kind: 'text' },
      { key: 'label', label: 'Label', kind: 'text', required: true },
      { key: 'description', label: 'Description', kind: 'textarea', rows: 3 },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'skill-categories',
    className: 'SkillCategory',
    label: 'Skill categories',
    singularLabel: 'skill category',
    description:
      'Shared skill sections used by resume rendering and opportunity matching.',
    icon: 'tag',
    orderBy: 'sortOrder ASC',
    tableColumns: ['categoryKey', 'label', 'sortOrder', 'updated_at'],
    fields: [
      {
        key: 'categoryKey',
        label: 'Category key',
        kind: 'text',
        required: true,
      },
      { key: 'label', label: 'Label', kind: 'text', required: true },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'skills',
    className: 'SkillCategoryMember',
    label: 'Skills',
    singularLabel: 'skill',
    description: 'Shared skill catalog backed by SMRT tag ids.',
    icon: 'tag',
    orderBy: 'sortOrder ASC',
    tableColumns: ['tagId', 'label', 'categoryId', 'sortOrder', 'updated_at'],
    fields: [
      tagIdField(),
      comboField('categoryId', 'Category', {
        className: 'SkillCategory',
        createKey: 'label',
        labelKey: 'label',
        snapshotKey: undefined,
      }),
      { key: 'label', label: 'Label', kind: 'text', required: true },
      {
        key: 'useOnResume',
        label: 'Use on resume',
        kind: 'checkbox',
        defaultValue: true,
        description: 'Show this skill in the resume Technical Skills section.',
      },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'skill-groups',
    className: 'SkillGroup',
    label: 'Skill groups',
    singularLabel: 'skill group',
    description:
      'Shared high-level skill themes used for filtering, tailoring, and matching.',
    icon: 'tag',
    orderBy: 'sortOrder ASC',
    tableColumns: ['groupKey', 'label', 'sortOrder', 'updated_at'],
    fields: [
      { key: 'groupKey', label: 'Group key', kind: 'text', required: true },
      { key: 'label', label: 'Label', kind: 'text', required: true },
      { key: 'blurb', label: 'Blurb', kind: 'textarea', rows: 2 },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'skill-group-members',
    className: 'SkillGroupMember',
    label: 'Skill group members',
    singularLabel: 'skill group member',
    description: 'SMRT skill tags included in shared skill groups.',
    icon: 'layers',
    orderBy: 'sortOrder ASC',
    tableColumns: ['groupId', 'tagId', 'sortOrder', 'updated_at'],
    fields: [
      comboField('groupId', 'Group', {
        className: 'SkillGroup',
        createKey: 'label',
        labelKey: 'label',
      }),
      tagIdField(),
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'experience',
    className: 'Experience',
    label: 'Experience',
    singularLabel: 'experience item',
    description: 'Professional experience source entries.',
    icon: 'briefcase',
    orderBy: 'sortOrder ASC',
    tableColumns: [
      'experienceKey',
      'url',
      'projectNames',
      'startDate',
      'endDate',
      'weight',
      'updated_at',
    ],
    fields: [
      {
        key: 'experienceKey',
        label: 'Experience key',
        kind: 'text',
        required: true,
      },
      { key: 'url', label: 'URL', kind: 'text' },
      { key: 'summary', label: 'Summary', kind: 'textarea', rows: 4 },
      { key: 'startDate', label: 'Start date', kind: 'date', required: true },
      { key: 'endDate', label: 'End date', kind: 'date' },
      {
        key: 'startPrecision',
        label: 'Start precision',
        kind: 'select',
        options: ['day', 'month', 'year'],
      },
      {
        key: 'endPrecision',
        label: 'End precision',
        kind: 'select',
        options: ['day', 'month', 'year', 'present'],
      },
      { key: 'weight', label: 'Weight', kind: 'number', defaultValue: 0 },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'experience-companies',
    className: 'ExperienceCompany',
    label: 'Experience companies',
    singularLabel: 'experience company',
    description: 'Company joins for experience entries.',
    icon: 'building',
    orderBy: 'sortOrder ASC',
    tableColumns: [
      'experienceId',
      'companyNameSnapshot',
      'relationship',
      'isPrimary',
      'updated_at',
    ],
    fields: [
      comboField('experienceId', 'Experience', {
        className: 'Experience',
        createKey: 'experienceKey',
        labelKey: 'experienceKey',
      }),
      comboField('companyId', 'Company', {
        className: 'Company',
        createKey: 'name',
        labelKey: 'name',
        snapshotKey: 'companyNameSnapshot',
      }),
      {
        key: 'relationship',
        label: 'Relationship',
        kind: 'text',
        defaultValue: 'employer',
      },
      {
        key: 'companyNameSnapshot',
        label: 'Company name snapshot',
        kind: 'text',
      },
      {
        key: 'companyHrefSnapshot',
        label: 'Company URL snapshot',
        kind: 'text',
      },
      {
        key: 'isPrimary',
        label: 'Primary',
        kind: 'checkbox',
        defaultValue: true,
      },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'experience-roles',
    className: 'ExperienceRole',
    label: 'Experience roles',
    singularLabel: 'experience role',
    description: 'Role joins and role date ranges for experience entries.',
    icon: 'briefcase',
    orderBy: 'sortOrder ASC',
    tableColumns: [
      'experienceId',
      'titleSnapshot',
      'startDate',
      'endDate',
      'updated_at',
    ],
    fields: [
      comboField('experienceId', 'Experience', {
        className: 'Experience',
        createKey: 'experienceKey',
        labelKey: 'experienceKey',
      }),
      comboField('roleId', 'Role', {
        className: 'EmploymentRole',
        createKey: 'label',
        labelKey: 'label',
        snapshotKey: 'titleSnapshot',
      }),
      {
        key: 'titleSnapshot',
        label: 'Title snapshot',
        kind: 'text',
        required: true,
      },
      { key: 'startDate', label: 'Start date', kind: 'date' },
      { key: 'endDate', label: 'End date', kind: 'date' },
      {
        key: 'startPrecision',
        label: 'Start precision',
        kind: 'select',
        options: ['day', 'month', 'year'],
      },
      {
        key: 'endPrecision',
        label: 'End precision',
        kind: 'select',
        options: ['day', 'month', 'year', 'present'],
      },
      { key: 'summary', label: 'Role summary', kind: 'textarea', rows: 3 },
      {
        key: 'isPrimary',
        label: 'Primary',
        kind: 'checkbox',
        defaultValue: true,
      },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'projects',
    className: 'Project',
    label: 'Projects',
    singularLabel: 'project',
    description: 'Projects and workstreams inside experience entries.',
    icon: 'layers',
    orderBy: 'sortOrder ASC',
    tableColumns: [
      'name',
      'url',
      'experienceId',
      'startDate',
      'endDate',
      'updated_at',
    ],
    fields: [
      comboField('experienceId', 'Experience', {
        className: 'Experience',
        createKey: 'experienceKey',
        labelKey: 'experienceKey',
      }),
      { key: 'projectKey', label: 'Project key', kind: 'text' },
      { key: 'name', label: 'Name', kind: 'text', required: true },
      { key: 'url', label: 'URL', kind: 'text' },
      { key: 'summary', label: 'Summary', kind: 'textarea', rows: 4 },
      { key: 'startDate', label: 'Start date', kind: 'date' },
      { key: 'endDate', label: 'End date', kind: 'date' },
      {
        key: 'startPrecision',
        label: 'Start precision',
        kind: 'select',
        options: ['day', 'month', 'year'],
      },
      {
        key: 'endPrecision',
        label: 'End precision',
        kind: 'select',
        options: ['day', 'month', 'year', 'present'],
      },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'duties',
    className: 'Duty',
    label: 'Duties',
    singularLabel: 'duty',
    description: 'Ongoing responsibilities attached to experience or projects.',
    icon: 'file-text',
    orderBy: 'sortOrder ASC',
    tableColumns: [
      'experienceId',
      'projectId',
      'title',
      'sortOrder',
      'updated_at',
    ],
    fields: [
      comboField('experienceId', 'Experience', {
        className: 'Experience',
        createKey: 'experienceKey',
        labelKey: 'experienceKey',
      }),
      comboField(
        'projectId',
        'Project',
        {
          className: 'Project',
          createKey: 'name',
          labelKey: 'name',
        },
        false,
      ),
      { key: 'title', label: 'Title', kind: 'text' },
      { key: 'body', label: 'Body', kind: 'textarea', rows: 4, required: true },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'achievements',
    className: 'Achievement',
    label: 'Achievements',
    singularLabel: 'achievement',
    description: 'Outcome bullets attached to experience or projects.',
    icon: 'file-text',
    orderBy: 'sortOrder ASC',
    tableColumns: [
      'experienceId',
      'projectId',
      'resumePlacement',
      'title',
      'metric',
      'updated_at',
    ],
    fields: [
      comboField('experienceId', 'Experience', {
        className: 'Experience',
        createKey: 'experienceKey',
        labelKey: 'experienceKey',
      }),
      comboField(
        'projectId',
        'Project',
        {
          className: 'Project',
          createKey: 'name',
          labelKey: 'name',
        },
        false,
      ),
      {
        key: 'resumePlacement',
        label: 'Resume placement',
        kind: 'select',
        options: ['auto', 'position', 'project', 'both'],
        defaultValue: 'auto',
        description:
          'Where this bullet appears on generated resumes. Auto shows project bullets under their project and role bullets under the company.',
      },
      { key: 'title', label: 'Title', kind: 'text', required: true },
      { key: 'body', label: 'Body', kind: 'textarea', rows: 5, required: true },
      { key: 'metric', label: 'Metric', kind: 'text' },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'education',
    className: 'Education',
    label: 'Education',
    singularLabel: 'education item',
    description: 'Education and certification source records.',
    icon: 'file-text',
    orderBy: 'sortOrder ASC',
    tableColumns: ['title', 'institution', 'sortOrder', 'updated_at'],
    fields: [
      {
        key: 'profileKey',
        label: 'Profile key',
        kind: 'text',
        defaultValue: 'default',
      },
      { key: 'title', label: 'Title', kind: 'text', required: true },
      { key: 'institution', label: 'Institution', kind: 'text' },
      {
        key: 'detail',
        label: 'Detail',
        kind: 'textarea',
        rows: 3,
        required: true,
      },
      { key: 'startDate', label: 'Start date', kind: 'date' },
      { key: 'endDate', label: 'End date', kind: 'date' },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'attachments',
    className: 'Attachment',
    label: 'Attachments',
    singularLabel: 'attachment',
    description:
      'Files stored in @happyvertical/files and attached to profile source records.',
    icon: 'file-text',
    orderBy: 'sortOrder ASC',
    tableColumns: ['title', 'kind', 'filePath', 'visibility', 'updated_at'],
    fields: [
      { key: 'filePath', label: 'File path', kind: 'text', required: true },
      {
        key: 'kind',
        label: 'Kind',
        kind: 'select',
        options: ['image', 'document', 'link', 'video', 'other'],
      },
      { key: 'title', label: 'Title', kind: 'text', required: true },
      { key: 'caption', label: 'Caption', kind: 'textarea', rows: 3 },
      { key: 'altText', label: 'Alt text', kind: 'text' },
      { key: 'mimeType', label: 'MIME type', kind: 'text' },
      { key: 'width', label: 'Width', kind: 'number' },
      { key: 'height', label: 'Height', kind: 'number' },
      { key: 'sourceUrl', label: 'Source URL', kind: 'text' },
      {
        key: 'visibility',
        label: 'Visibility',
        kind: 'select',
        options: ['public', 'private', 'confidential'],
      },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'resume-tailoring-configs',
    className: 'ResumeTailoringConfig',
    label: 'Tailoring configs',
    singularLabel: 'tailoring config',
    description: 'Named resume variants for roles, companies, and audiences.',
    icon: 'sliders',
    orderBy: 'name ASC',
    tableColumns: ['configSlug', 'name', 'company', 'active', 'updated_at'],
    fields: [
      { key: 'configSlug', label: 'Slug', kind: 'text', required: true },
      { key: 'name', label: 'Name', kind: 'text', required: true },
      { key: 'company', label: 'Company', kind: 'text' },
      {
        key: 'configJson',
        label: 'Config JSON',
        kind: 'textarea',
        rows: 12,
        required: true,
      },
      { key: 'active', label: 'Active', kind: 'checkbox', defaultValue: true },
    ],
  },
  {
    slug: 'opportunity-tags',
    className: 'OpportunityTag',
    label: 'Opportunity tags',
    singularLabel: 'Opportunity tag',
    description: 'Tag assignments for skills, domains, and role taxonomy.',
    icon: 'tag',
    orderBy: 'updated_at DESC',
    tableColumns: ['opportunityId', 'tagRole', 'tagId', 'updated_at'],
    fields: [
      {
        key: 'opportunityId',
        label: 'Opportunity ID',
        kind: 'text',
        required: true,
      },
      tagIdField(),
      {
        key: 'tagRole',
        label: 'Tag role',
        kind: 'select',
        options: [
          'required_skill',
          'preferred_skill',
          'domain',
          'role',
          'industry',
          'general',
        ],
      },
    ],
  },
  {
    slug: 'opportunity-places',
    className: 'OpportunityPlace',
    label: 'Opportunity places',
    singularLabel: 'Opportunity place',
    description: 'Structured job, hybrid, relocation, and timezone places.',
    icon: 'map-pin',
    orderBy: 'updated_at DESC',
    tableColumns: ['opportunityId', 'placeRole', 'placeId', 'updated_at'],
    fields: [
      {
        key: 'opportunityId',
        label: 'Opportunity ID',
        kind: 'text',
        required: true,
      },
      placeIdField(),
      {
        key: 'placeRole',
        label: 'Place role',
        kind: 'select',
        options: [
          'job_location',
          'hybrid_region',
          'relocation_target',
          'timezone_region',
        ],
      },
    ],
  },
  {
    slug: 'opportunity-roles',
    className: 'OpportunityRole',
    label: 'Opportunity roles',
    singularLabel: 'Opportunity role',
    description: 'Normalized role taxonomy attached to opportunities.',
    icon: 'briefcase',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'opportunityId',
      'titleSnapshot',
      'roleId',
      'seniority',
      'updated_at',
    ],
    fields: [
      {
        key: 'opportunityId',
        label: 'Opportunity ID',
        kind: 'text',
        required: true,
      },
      comboField('roleId', 'Role', {
        className: 'EmploymentRole',
        createKey: 'label',
        labelKey: 'label',
        snapshotKey: 'titleSnapshot',
      }),
      {
        key: 'titleSnapshot',
        label: 'Title snapshot',
        kind: 'text',
        required: true,
      },
      {
        key: 'seniority',
        label: 'Seniority',
        kind: 'select',
        options: [
          'senior',
          'staff',
          'principal',
          'founding',
          'lead',
          'exec',
          'unknown',
        ],
      },
      {
        key: 'source',
        label: 'Source',
        kind: 'select',
        options: ['manual', 'posting', 'agent', 'import'],
      },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'source-tags',
    className: 'SourceTag',
    label: 'Source tags',
    singularLabel: 'Source tag',
    description: 'Taxonomy attached to job sources and search feeds.',
    icon: 'tag',
    orderBy: 'updated_at DESC',
    tableColumns: ['sourceId', 'tagRole', 'tagId', 'updated_at'],
    fields: [
      { key: 'sourceId', label: 'Source ID', kind: 'text', required: true },
      tagIdField(),
      {
        key: 'tagRole',
        label: 'Tag role',
        kind: 'select',
        options: ['source', 'industry', 'role', 'market', 'general'],
      },
    ],
  },
  {
    slug: 'decision-tags',
    className: 'DecisionTag',
    label: 'Decision tags',
    singularLabel: 'Decision tag',
    description: 'Structured reason taxonomy attached to decisions.',
    icon: 'tag',
    orderBy: 'updated_at DESC',
    tableColumns: ['decisionId', 'tagRole', 'tagId', 'updated_at'],
    fields: [
      { key: 'decisionId', label: 'Decision ID', kind: 'text', required: true },
      tagIdField(),
      {
        key: 'tagRole',
        label: 'Tag role',
        kind: 'select',
        options: ['reason', 'preference', 'risk', 'upside', 'general'],
      },
    ],
  },
  {
    slug: 'company-tags',
    className: 'CompanyTag',
    label: 'Company tags',
    singularLabel: 'company tag',
    description: 'SMRT tag assignments for companies.',
    icon: 'tag',
    orderBy: 'updated_at DESC',
    tableColumns: ['companyId', 'tagRole', 'tagId', 'updated_at'],
    fields: [
      comboField('companyId', 'Company', {
        className: 'Company',
        createKey: 'name',
        labelKey: 'name',
      }),
      tagIdField(),
      {
        key: 'tagRole',
        label: 'Tag role',
        kind: 'select',
        options: ['industry', 'domain', 'technology', 'general'],
      },
    ],
  },
  {
    slug: 'role-tags',
    className: 'EmploymentRoleTag',
    label: 'Role tags',
    singularLabel: 'role tag',
    description: 'SMRT tag assignments for shared roles.',
    icon: 'tag',
    orderBy: 'updated_at DESC',
    tableColumns: ['roleId', 'tagRole', 'tagId', 'updated_at'],
    fields: [
      comboField('roleId', 'Role', {
        className: 'EmploymentRole',
        createKey: 'label',
        labelKey: 'label',
      }),
      tagIdField(),
      {
        key: 'tagRole',
        label: 'Tag role',
        kind: 'select',
        options: ['role', 'skill', 'domain', 'general'],
      },
    ],
  },
  {
    slug: 'experience-tags',
    className: 'ExperienceTag',
    label: 'Experience tags',
    singularLabel: 'experience tag',
    description: 'SMRT tag assignments for experience entries.',
    icon: 'tag',
    orderBy: 'updated_at DESC',
    tableColumns: ['experienceId', 'tagRole', 'tagId', 'updated_at'],
    fields: [
      comboField('experienceId', 'Experience', {
        className: 'Experience',
        createKey: 'experienceKey',
        labelKey: 'experienceKey',
      }),
      tagIdField(),
      {
        key: 'tagRole',
        label: 'Tag role',
        kind: 'select',
        options: ['skill', 'domain', 'role', 'industry', 'general'],
      },
    ],
  },
  {
    slug: 'project-tags',
    className: 'ProjectTag',
    label: 'Project tags',
    singularLabel: 'project tag',
    description: 'SMRT tag assignments for projects.',
    icon: 'tag',
    orderBy: 'updated_at DESC',
    tableColumns: ['projectId', 'tagRole', 'tagId', 'updated_at'],
    fields: [
      comboField('projectId', 'Project', {
        className: 'Project',
        createKey: 'name',
        labelKey: 'name',
      }),
      tagIdField(),
      {
        key: 'tagRole',
        label: 'Tag role',
        kind: 'select',
        options: ['skill', 'domain', 'role', 'general'],
      },
    ],
  },
  {
    slug: 'achievement-tags',
    className: 'AchievementTag',
    label: 'Achievement tags',
    singularLabel: 'achievement tag',
    description: 'SMRT tag assignments for achievements.',
    icon: 'tag',
    orderBy: 'updated_at DESC',
    tableColumns: ['achievementId', 'tagRole', 'tagId', 'updated_at'],
    fields: [
      comboField('achievementId', 'Achievement', {
        className: 'Achievement',
        createKey: 'title',
        labelKey: 'title',
      }),
      tagIdField(),
      {
        key: 'tagRole',
        label: 'Tag role',
        kind: 'select',
        options: ['skill', 'domain', 'role', 'general'],
      },
    ],
  },
  {
    slug: 'duty-tags',
    className: 'DutyTag',
    label: 'Duty tags',
    singularLabel: 'duty tag',
    description: 'SMRT tag assignments for duties.',
    icon: 'tag',
    orderBy: 'updated_at DESC',
    tableColumns: ['dutyId', 'tagRole', 'tagId', 'updated_at'],
    fields: [
      comboField('dutyId', 'Duty', {
        className: 'Duty',
        createKey: 'title',
        labelKey: 'title',
      }),
      tagIdField(),
      {
        key: 'tagRole',
        label: 'Tag role',
        kind: 'select',
        options: ['skill', 'domain', 'role', 'general'],
      },
    ],
  },
  {
    slug: 'education-tags',
    className: 'EducationTag',
    label: 'Education tags',
    singularLabel: 'education tag',
    description: 'SMRT tag assignments for education.',
    icon: 'tag',
    orderBy: 'updated_at DESC',
    tableColumns: ['educationId', 'tagRole', 'tagId', 'updated_at'],
    fields: [
      comboField('educationId', 'Education', {
        className: 'Education',
        createKey: 'title',
        labelKey: 'title',
      }),
      tagIdField(),
      {
        key: 'tagRole',
        label: 'Tag role',
        kind: 'select',
        options: ['skill', 'domain', 'credential', 'general'],
      },
    ],
  },
  {
    slug: 'company-attachments',
    className: 'CompanyAttachment',
    label: 'Company attachments',
    singularLabel: 'company attachment',
    description: 'Logos and files attached to companies.',
    icon: 'file-text',
    orderBy: 'sortOrder ASC',
    tableColumns: [
      'companyId',
      'attachmentId',
      'usage',
      'sortOrder',
      'updated_at',
    ],
    fields: [
      comboField('companyId', 'Company', {
        className: 'Company',
        createKey: 'name',
        labelKey: 'name',
      }),
      comboField('attachmentId', 'Attachment', {
        className: 'Attachment',
        createKey: 'title',
        labelKey: 'title',
      }),
      {
        key: 'usage',
        label: 'Usage',
        kind: 'select',
        options: ['logo', 'artifact', 'research', 'other'],
      },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'project-attachments',
    className: 'ProjectAttachment',
    label: 'Project attachments',
    singularLabel: 'project attachment',
    description: 'Screenshots, documents, and artifacts attached to projects.',
    icon: 'file-text',
    orderBy: 'sortOrder ASC',
    tableColumns: [
      'projectId',
      'attachmentId',
      'usage',
      'sortOrder',
      'updated_at',
    ],
    fields: [
      comboField('projectId', 'Project', {
        className: 'Project',
        createKey: 'name',
        labelKey: 'name',
      }),
      comboField('attachmentId', 'Attachment', {
        className: 'Attachment',
        createKey: 'title',
        labelKey: 'title',
      }),
      {
        key: 'usage',
        label: 'Usage',
        kind: 'select',
        options: ['screenshot', 'evidence', 'artifact', 'other'],
      },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'achievement-attachments',
    className: 'AchievementAttachment',
    label: 'Achievement attachments',
    singularLabel: 'achievement attachment',
    description:
      'Screenshots, evidence, and artifacts attached to achievements.',
    icon: 'file-text',
    orderBy: 'sortOrder ASC',
    tableColumns: [
      'achievementId',
      'attachmentId',
      'usage',
      'sortOrder',
      'updated_at',
    ],
    fields: [
      comboField('achievementId', 'Achievement', {
        className: 'Achievement',
        createKey: 'title',
        labelKey: 'title',
      }),
      comboField('attachmentId', 'Attachment', {
        className: 'Attachment',
        createKey: 'title',
        labelKey: 'title',
      }),
      {
        key: 'usage',
        label: 'Usage',
        kind: 'select',
        options: ['screenshot', 'evidence', 'artifact', 'other'],
      },
      {
        key: 'sortOrder',
        label: 'Sort order',
        kind: 'number',
        defaultValue: 0,
      },
    ],
  },
  {
    slug: 'preferences',
    className: 'PreferenceRule',
    label: 'Preferences',
    singularLabel: 'Preference rule',
    description:
      'Hard filters and weighted rules for future recommendation scoring.',
    icon: 'sliders',
    orderBy: 'updated_at DESC',
    tableColumns: [
      'name',
      'category',
      'weight',
      'isHardFilter',
      'active',
      'updated_at',
    ],
    fields: [
      {
        key: 'category',
        label: 'Category',
        kind: 'select',
        options: [
          'compensation',
          'location',
          'role',
          'company',
          'contract',
          'equity',
          'exclusion',
          'scoring',
        ],
      },
      { key: 'name', label: 'Name', kind: 'text', required: true },
      { key: 'description', label: 'Description', kind: 'textarea', rows: 4 },
      { key: 'weight', label: 'Weight', kind: 'number' },
      { key: 'isHardFilter', label: 'Hard filter', kind: 'checkbox' },
      {
        key: 'ruleJson',
        label: 'Rule JSON',
        kind: 'textarea',
        rows: 5,
        description: agentJsonFieldDescription,
      },
      { key: 'active', label: 'Active', kind: 'checkbox' },
    ],
  },
];

export function getAdminResource(slug: string): AdminResource | undefined {
  return adminResources.find((resource) => resource.slug === slug);
}
