apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iolaus-self-hosted

resources:
  - namespace.yaml
  - service.yaml
  - web-deployment.yaml
  - task-worker-deployment.yaml
  - schedule-worker-deployment.yaml
  - web-pod-disruption-budget.yaml
  - queue-provider-monitor.yaml
